prebuilt_cxx_library(
  name = 'test', 
  header_namespace = '', 
  header_only = True, 
  exported_headers = subdir_glob([
    ('include', '**/*.hpp'), 
  ]), 
  deps = [
    '//test/catch:catch', 
  ], 
  visibility = [
    'PUBLIC', 
  ], 
)
